### ISSUE TITLE
neq: null 和 eq: null 无效

### ISSUE THREAD

**Issue by mapleincode** [XadillaX/Toshihiko#52]
已设置`allowNull: true`。

`{ column: { eq: null } }`和 `{ column: { neq: null }}`均无法生成 sql。只有`{ column: null }`才可以。

**Comment by XadillaX** [comment]
应该是 `{ $eq: null }` 和 `{ $neq: null }`。

**Comment by mapleincode** [comment]
_(:з」∠)_   ヾ(｡｀Д´｡) 这是意外
