### ISSUE TITLE
这个库不带关联？

### ISSUE THREAD

**Issue by simdm** [XadillaX/Toshihiko#60]
这个库不带关联？
1：1 
1：n 
n:m

**Comment by XadillaX** [comment]
是的，出于性能考虑，该 ORM 不提供联表操作，仅提供高性能查询的 API 们。

而且定位就是**简单**高效的 ORM。

**Comment by simdm** [comment]
建议加上，这样太有局限性了，加上用的人会多很多，现在无法表示稍微复杂一点的数据逻辑，ORM中的R很重要的。
