### ISSUE TITLE
唯一值

### ISSUE THREAD

**Issue by zhongguolu** [XadillaX/Toshihiko#77]
可否加一个唯一值判断字段，在过滤函数里写挺麻烦的.....

**Comment by XadillaX** [comment]
-。 - 什么叫唯一值判断字段？

**Comment by zhongguolu** [comment]
额 就是类似allowNo 这个字段，提供一个字段，在添加或删除的时候自动验证唯一性

**Comment by XadillaX** [comment]
这个是可以通过数据库自己的 unique 索引来吧？
