### ISSUE TITLE
关于：validators

### ISSUE THREAD

**Issue by zhongguolu** [XadillaX/Toshihiko#78]
能否加入异步判断机制，来解决比如判断唯一性的问题，现在似乎只能是在orm本身上写自定义方法或者在orm外，而且这种情况比较频繁

**Comment by XadillaX** [comment]
可以考虑提上日程。

**Comment by XadillaX** [comment]
在 1.* 的版本中已经加入该特性了。

**Comment by XadillaX** [comment]
https://github.com/XadillaX/Toshihiko/commit/04636269fdb9c049868a6ff48d6166b46b439221

已有提交，等待 alpha 发布。
